server:
  port: 9900

spring:
  datasource:
    #jdbc:mysql://localhost:3456/mh_db cos cos1234
    url: jdbc:mysql://localhost:3456/mh_db  #jdbc:mysql://192.168.11.135:3456/bdBase mhui123 1234
    username: cos
    password: cos1234
    driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update #create create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
  #        use_sql_comments: true #쿼리 추가정보 출력
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
