server:
#  servlet:
#    context-path: /mhproject
  port: 9900

jwt:
  secret: 6158b0e1443afadfd0538986e2a135025349bd59045b6c11da7fdc04194f1043
logging:
  level:
    root: info
  console:
    enabled: true
    threshold: debug
spring:
  datasource:
    #집
#        url: jdbc:mysql://localhost:3456/mh_db
#        username: cos
#        password: cos1234
#        driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
    #도커용.
#    url: jdbc:mysql://docker-mysql:3306/mh_db
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
    #회사
#      url: jdbc:mysql://192.168.11.135:3456/bdBase
      url: jdbc:mysql://localhost:3555/mh_db
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver #org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update #create create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
  #        use_sql_comments: true #쿼리 추가정보 출력

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
